# ALEX'S BASH ALIASES

# ls
alias l='ls --color'
alias ll='ls -lahv --color --group-directories-first'
alias l.s='ls -lahS --color'                    # sort by size
alias l.t='ls -lahtc --color --time-style=iso'  # sort by mtime
alias l.u='ls -lahtu --color --time-style=iso'  # sort by atime

# cd
alias c='cd'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

# editor
alias e='nvim'

# reader
alias r='less'
alias r.f='less -nR +F'

# open
alias o='xdg-open'

# git
alias g.s='git status'                          # status
alias g.k='gitk --all'                          # GUI (readonly)
alias g.l='git log --oneline --graph'           # log
alias g.t='git log --tags --simplify-by-decoration --pretty="format:%<(16)%D - %h - %ar"'  # tags
alias g.d='git diff --minimal -U1 -w'           # diff
alias g.dt='git difftool -y'                    # diff tool
alias g.f='git pull --all --prune'              # fetch + merge
alias g.fr='git pull --all --prune --rebase'    # fetch + rebase
alias g.c='git add --all && git commit'         # add + commit
alias g.x='git clean -fd && git reset --hard'   # discard all
alias g.p='git push'                            # push
alias g.b='git checkout'                        # checkout <branch>
alias g.ba='git branch --all'                   # list branchs
alias g.m='git merge'                           # merge <branch>
alias g.ma='git merge --abort'                  # merge abort
alias g.mt='git mergetool -y'                   # merge tool
alias g.Fi='git flow init'                      # git-flow init
alias g.Ffs='git flow feature start -F'         # feature start <name>
alias g.Fff='git flow feature finish -F'        # feature finish <name>
alias g.Fbs='git flow bugfix start -F'          # bugfix start <name>
alias g.Fbf='git flow bugfix finish -F'         # bugfix finish <name>
alias g.Frs='git flow release start -F'         # release start <version>
alias g.Frf='git flow release finish -pF'       # release finish <version>
alias g.Fhs='git flow hotfix start -F'          # hotfix start <version>
alias g.Fhf='git flow hotfix finish -pF'        # hotfix finish <version>

# mvn
alias m.c='mvn -o -T 1C compile'                # compile
alias m.t='mvn test'                            # test
alias m.p='mvn clean package -U'                # package
alias m.i='mvn clean install -P release'        # install release
alias m.v='mvn versions:set'                    # set version (interactive)
alias m.d='mvn dependency:get'                  # dependency get
alias m.dt='mvn dependency:tree -Dverbose'      # dependency tree
alias m.da='mvn dependency:analyze'             # dependency analyze
alias m.do='mvn de.qaware.maven:go-offline-maven-plugin:resolve-dependencies -DdownloadSources -DdownloadJavadoc; mvn clean install -DskipTests=true'  # go offline
alias m.w='mvn -N io.takari:maven:wrapper'      # maven wrapper

